Verify pf exists, split pf reading into function

diff --git a/mk_deployment_movies b/mk_deployment_movies
--- a/mk_deployment_movies
+++ b/mk_deployment_movies
@@ -16,6 +16,16 @@ TMPDIR="/tmp/mk_deployment_movies.$$"
 DEPLOYTYPES="seismic inframet"
 HISTTYPES="cumulative rolling"
 
+### The following variables are set in load_pf_globals
+# Directory where map images are located
+declare -A MAPDIR
+# Prefix to map image file
+declare -A MAPPREFIX
+# Directory where movie files are located
+declare -A MOVDIR
+# Prefix to movie file
+declare -A MOVPREFIX
+
 ### Functions
 
 # pfghetto
@@ -174,30 +184,41 @@ function set_prev_year_month {
   unset tyear tmonth
 }
 
+function validate_pf {
+  local mypfname=$1
+  if [ "$(pfecho -w $mypfname)" != '' ] ; then return 0; fi
+  echo "Can't find parameter file \"$mypfname\"" 1>&2
+  return 1
+}
+
+function load_pf_globals {
+  # Directory where map images are located
+  MAPDIR["seismic"]=$(pfghetto $PFNAME CACHE_MONTHLY_DEPLOYMENT)
+  MAPDIR["inframet"]=$(pfghetto $PFNAME CACHE_MONTHLY_DEPLOYMENT_INFRA)
+
+  # Prefix to map image file
+  MAPPREFIX["seismic"]="deploymap_"
+  MAPPREFIX["inframet"]="deploymap_inframet_"
+
+  # Directory where movie files are located
+  MOVDIR["seismic"]=$(pfghetto $PFNAME CACHE_MOV_MONTHLY_DEPLOYMENT)
+  MOVDIR["inframet"]=$(pfghetto $PFNAME CACHE_MOV_MONTHLY_DEPLOYMENT_INFRA)
+
+  # Prefix to movie file
+  MOVPREFIX["seismic"]="deployment_"
+  MOVPREFIX["inframet"]="inframet_deployment_"
+
+  return 0
+}
+
 
 ### Main ###
 
+validate_pf $PFNAME || exit 1
+
+load_pf_globals
+
 ### load parameters from parameter file
-
-# Directory where map images are located
-declare -A MAPDIR
-MAPDIR["seismic"]=$(pfghetto $PFNAME CACHE_MONTHLY_DEPLOYMENT)
-MAPDIR["inframet"]=$(pfghetto $PFNAME CACHE_MONTHLY_DEPLOYMENT_INFRA)
-
-# Prefix to map image file
-declare -A MAPPREFIX
-MAPPREFIX["seismic"]="deploymap_"
-MAPPREFIX["inframet"]="deploymap_inframet_"
-
-# Directory where movie files are located
-declare -A MOVDIR
-MOVDIR["seismic"]=$(pfghetto $PFNAME CACHE_MOV_MONTHLY_DEPLOYMENT)
-MOVDIR["inframet"]=$(pfghetto $PFNAME CACHE_MOV_MONTHLY_DEPLOYMENT_INFRA)
-# Prefix to movie file
-declare -A MOVPREFIX
-MOVPREFIX["seismic"]="deployment_"
-MOVPREFIX["inframet"]="inframet_deployment_"
-
 
 # Since this script is intended to run at the beginning of the month
 # after the monthly image generation script, it will only have images
